default_keywords = [
    "Municipal Form No. 102",
    "(To be accomplished in quadruplicate using black ink)",
    "(Revised January 2007)",
    "Republic of the Philippines",
    "OFFICE OF THE CIVIL REGISTRAR GENERAL",
    "CERTIFICATE OF LIVE BIRTH",
    "Registry No",
    "Province",
    "City/Municipality",
    "1 , NAME",
    "(First)",
    "(Middle)",
    "(Last)",
    "2. SEX (Male / Female)",
    "3. DATE OF",
    "(Day)",
    "(Month)",
    "(Year)",
    "BIRTH",
    "4.PLACE OF",
    "Hoase",
    "of Hospital/CliniclInstitutionl",
    "(CitylMunicipality)",
    "(Province)",
    "6",
    "BIRTH",
    "St , Barangay)",
    "5a. TYPE OF BIRTH",
    "5b. IF MULTIPLE BIRTH, CHILD WAS",
    "Sc.BIRTH ORDER (Order of this birth lo",
    "6.WEIGHTAT BIRTH",
    "Single Twin Triplet; etc; _",
    "(Firsl, Second; Third",
    "etc: )",
    "previous live births inclucing ietal death)",
    "(First  Second, Third,",
    "etc:",
    "grams",
    "7 . MAIDEN",
    "(First)",
    "(Middle)",
    "(Last)",
    "NAME",
    "8.CITIZENSHIP",
    "9.RELIGIONIRELIGIOUS SECT",
    "1",
    "1Oa_",
    "Total number of",
    "10b_",
    "No",
    "of children still",
    "10c_",
    "No. of children",
    "born",
    "11. OCCUPATION",
    "12. AGE at the",
    "of this",
    "children born alive",
    "including this birth",
    "alive but are now dead",
    "birth (completed years)",
    "13. RESIDENCE",
    "(House No_",
    "St , Barangay)",
    "(CitylMunicipality)",
    "(Province)",
    "(Country)",
    "14. NAME",
    "(First)",
    "(Middle)",
    "(Last)",
    "15. CITIZENSHIP",
    "16. RELIGIONIRELIGIOUS SECT",
    "17. OCCUPATION",
    "18.  AGE at the time of this",
    "1",
    "birth (completed years)",
    "19. RESIDENCE",
    "(House No:, St . Barangay)",
    "(CitylMunicipality)",
    "Province)",
    "Country)",
    "MARRIAGE OF PARENTS (If not married, accomplish Affdavit of AcknowledgementAdmission of Paternity at the back:)",
    "20a. DATE",
    "(Month)",
    "(Day)",
    "(Year)",
    "20b. PLACE",
    "Municipality)",
    "(Province)",
    "(Country)",
    "21a.ATTENDANT",
    "Physician",
    "2 Nurse",
    "Midwife",
    "Hilot (Traditional Birth Attendant)",
    "Others (Specify)",
    "21b. CERTIFICATION OF ATTENDANT AT BIRTH (Physician, Nurse, Midwife, Traditional Birth AttendanuHilot; etc: )",
    "hereby certify that",
    "attended the birth of the child who was born alive at",
    "amlpm",
    "on the date of birth specified above",
    "Signature",
    "Address",
    "Name in Print",
    "Title",
    "Position",
    "Date",
    "22. CERTIFICATION OF INFORMANT",
    "23.PREPARED BY",
    "hereby certify that all information supplied are true and",
    "correct to my own knowledge and belief.",
    "Signature",
    "Signature",
    "Name in Print",
    "Name in Print",
    "Relationship to the Child",
    "Title",
    "Position",
    "Address",
    "Date",
    "Date",
    "24.RECEIVED BY",
    "25.REGISTERED BY THE CIVIL REGISTRAR",
    "Signature",
    "Signature",
    "Name in Print",
    "Name in Print",
    "Title",
    "Position",
    "Title or Position",
    "Date",
    "Date",
    "REMARKSIANNOTATIONS (For LCROIOCRG Use Only)",
    "To BE FILLED-UP AT THE OFFICE OF THE CIVIL REGISTRAR",
    "13",
    "15",
    "16",
    "No-.",
    "time",
    "living",
    "(City",
    "AFFIDAVIT OF ACKNOWLEDGMENTIADMISSION OF PATERNITY",
    "(For births before 3 August 1988)",
    "(For births on or after 3 August 1988)",
    "IWe,",
    "and",
    "of legal age, amlare the natural mother andlor father of",
    "who",
    "was",
    "born",
    "on",
    "am",
    "We are",
    "executing this affidavit to attest to the truthfulness of the foregoing statements and for purposes of|",
    "acknowledging mylour child.",
    "(Signature Over Printed Name of Father)",
    "(Signature Over Printed Name of Mother)",
    "SUBSCRIBED AND SWORN",
    "to before me this",
    "day of",
    "by",
    "and",
    "who exhibited to me (his/her)",
    "Community",
    "Tax",
    "Cert: No",
    "issued",
    "on",
    "at",
    "Signature of the Administering Officer",
    "Position",
    "Title",
    "Designation",
    "Name in Print",
    "Address",
    "AFFIDAVIT FOR DELAYED REGISTRATION OF BIRTH",
    "(To be accomplished by the hospitallclinic administrator; father, mother; or guardian or the person himself if 18 years old or over:)",
    "of legal age, singlelmarried/divorcedlwidowlwidower; with",
    "residence and postal address",
    "after",
    "been",
    "sworn in accordance with law;",
    "do hereby  depose and say:",
    "That",
    "am the applicant for the delayed registration of:",
    "my birth in",
    "on",
    "the birth of",
    "who was born in",
    "on",
    "That Ilhelshe was attended at birth by",
    "who resides at",
    "That",
    "amlhelshe",
    "is a citizen of",
    "That mylhislher parents were",
    "married on",
    "not married but Ilhelshe was acknowledgedlnot acknowledged by mylhislher",
    "father whose",
    "name is",
    "5. That the reason for the delay in registering mylhislher birth was",
    "(For the applicant only)",
    "That",
    "am married to",
    "(If the applicant is other than the document owner)",
    "That",
    "am the",
    "of the said person_",
    "That",
    "am executing this affidavit to attest to the truthfulness of the foregoing statements for all legal intents and purposes.",
    "In truth whereof,",
    "have affixed my signature below this",
    "of",
    "at",
    "Philippines ",
    "(Signature Over Printed Name of Affiant)",
    "SUBSCRIBED AND SWORN",
    "to before me this",
    "day of",
    "at",
    "Philippines, affiant who exhibited to me his Community Tax Cert",
    "issued on",
    "Signature of the Administering Officer",
    "Position",
    "Title / Designation",
    "Name in Print",
    "Address",
    "having",
    "duly",
    "day"
]

def parse(ocr_text):
    text = []
    for word in ocr_text: 
        text.append(word)

    return text