from rapidfuzz import fuzz, process
from difflib import SequenceMatcher
import os
import re
from datetime import datetime
from logger_setup import setup_logger
logger = setup_logger(__name__, "python-backend/logs/marriage_parser.log")

default_keywords = [
  "Municipal Form No. 97",
  "Republic of the_Philippines",
  "(To be accomplished in quadruplicate using black ink)",
  "(Revised January",
  "OFFICE OF THE CIVIL REGISTRAR GENERAL",
  "CERTIFICATE",
  "OF MARRIAGE",
  "Province",
  "Registry No",
  "CitylMunicipality",
  "HUSBAND",
  "WIFE",
  "Name of",
  "(First)",
  "(First)",
  "Contracting",
  "Parties",
  "(Middle)",
  "(Middle)",
  "(Last)",
  "(Last)",
  "2a",
  "Date of Birth",
  "(Month)",
  "(Year)",
  "(Age)",
  "(Day)",
  "(Month)",
  "(Year)",
  "(Age)",
  "2b.",
  "3. Place of Birth",
  "(City Municipality)",
  "(Province)",
  "(Country)",
  "(City/Municipality)",
  "(Province)",
  "(Country)",
  "4a_",
  "Sex",
  "(Citizenship)",
  "(Citizenship)",
  "4b. Citizenship",
  "5 , Residence",
  "(House No . St , Barangay; CitylMunicipality, Province",
  "Country)",
  "(House",
  "Barangay   CilyiMunicipalily, Province, Country)",
  "6. Religion/",
  "Religious Sect",
  "7 . Civil Status",
  "Name of",
  "(First)",
  "(Middle)",
  "(Last)",
  "(First)",
  "(Middle}",
  "(Last)",
  "Father",
  "Citizenship",
  "10. Maiden Name",
  "(First)",
  "(Middle)",
  "(Last)",
  "(First)",
  "(Middle)",
  "(Last)",
  "of Mother",
  "Citizenship",
  "12, Name 0i Person/",
  "(First)",
  "(Middle)",
  "(Last)",
  "(First)",
  "(Middle)",
  "(Lasu)",
  "Wali Who Gave",
  "Consent or",
  "Advice",
  "13. Relationship",
  "(Hause",
  "No.",
  "Barangay: Cily/Municipality. Province , Country)",
  "(House No;",
  "SL . Barangay; CitylMunicipalily Province , Country)",
  "14.",
  "Residence",
  "15_",
  "Place of Marriage:",
  "(Office of thelHouse",
  "ofIBarangay ofiChurch ofiMosque of)",
  "\"(CitylMunicipality)",
  "(Province)",
  "16. Date of Marriage:",
  "17.",
  "Time of Marriage:",
  "amlpm",
  "(Day)",
  "(Month)",
  "(Year)",
  "18 . CERTIFICATION",
  "OF",
  "THE CONTRACTING PARTIES:",
  "This IS",
  "To",
  "CERTIFY: That",
  "and",
  "both",
  "legal age;",
  "of our own free will and accord",
  "and in the presence of the person solemnizing this marriage and of the witnesses named below, take each other",
  "as husband and wife",
  "certifying further that we:",
  "have entered;",
  "a copy of which is hereto attached",
  "have not entered into a marriage settlement:",
  "IN WITNESS WHEREOF",
  "we have",
  "signed Imarked with our fingerprint this certificate in quadruplicate this",
  "'(Signature 0f 'Husband)'",
  "(Signature of Wife)",
  "19, CERTIFICATION OF THE SOLEMNIZING OFFICER:",
  "THIS IS TO CERTIFY:",
  "THAT BEFORE ME,",
  "on the date and place above-written_",
  "personally appeared the above-mentioned parties",
  "with",
  "their mutual consent, lawfully joined together in marriage which",
  "was",
  "solemnized by",
  "me in the presence of the witnesses named below, all of legal age",
  "CERTIFY FURTHER THAT:",
  "Marriage License No",
  "issued on",
  "in favor of saia parties",
  "was",
  "exhibited to me",
  "no marriage license was necessary, Ihe marriage being solemnized under Art:",
  "of Executive Order No. 209.",
  "the marriage",
  "was solemnized in accordance with the provisions of Presidential Decree No. 1083.",
  "(Signature Over Printed Name of Solemnizing Officer)",
  "Position/Designation)",
  "(Religion/Religious",
  "Seci Rpglicableyo:",
  "-and",
  "Expiration",
  "Dale",
  "20a. WITNESSES (Print Name",
  "Sign):",
  "Additional",
  "at the back",
  "\"21, RECEIVED BY",
  "22.REGISTERED BY THE CIVIL REGISTRAR",
  "Signature",
  "Signature",
  "Name",
  "in Print",
  "Name in Print",
  "Title or Position",
  "Title or Position",
  "Date",
  "Date",
  "REMARKSIANNOTATIONS (For LCROIOCRGISharia Circuit Registrar Use Only)",
  "TO BE FILLED-UPAT THE OFFICE OF THE CIVIL REGISTRAR",
  "4bH",
  "AbW",
  "5H",
  "5w",
  "6H",
  "6W",
  "7H",
  "7W",
  "2007)",
  "(Day)",
  "Age",
  "No .",
  "and",
  "day",
  "and",
  "20b. WITNESSES (Print Name and Sign):",
  "AFFIDAVIT OF SOLEMNIZING OFFICER",
  "oflegal",
  "age,",
  "Solemnizing",
  "Officer",
  "with",
  "address",
  "after having",
  "sworn to in accordance wilh",
  "Iaw; do hereby depose and say:",
  "That",
  "have solemnized the marriage between",
  "and",
  "That",
  "have",
  "ascertained",
  "the",
  "qualifications",
  "the",
  "contracting",
  "parties",
  "and have found",
  "legal impediment for them t0",
  "marry",
  "as required by Article 34 of the Family Code;",
  "b. That",
  "this",
  "marriage was performed in articulo mortis or at the point of death;",
  "That the contracting partylies",
  "and",
  "being at the point of",
  "death",
  "and physically unable t0 sign the foregoing certificate of marriage by signature or mark,",
  "one 0f",
  "the witnesses to the marriage; sign",
  "for him or her by writing the dying party's name and beneath it, the witness\"",
  "own",
  "signature preceded by the preposition \"By\";",
  "That the residence of either party is So located",
  "there is",
  "means of",
  "transportation to enable concerned partylparties to appear",
  "personally before the civil registrar;",
  "That the marriage was among Muslims",
  "or among members of",
  "Ethnic Cultural Communities and that the marriage was solemnized",
  "in accordance with their customs",
  "and practices",
  "3. That",
  "took the necessary steps to ascertain the ages",
  "relationship of the contracting parties and that neither of",
  "them",
  "are under any legal",
  "impediment to marry",
  "each other;",
  "That",
  "am executing this affidavit to attest to the truthfulness of the foregoing statements for all Iegal intents and purposes",
  "truth",
  "whereof,",
  "have",
  "affixed",
  "my",
  "signature",
  "below",
  "this",
  "Philippines.",
  "Signature Over Printed Name of",
  "Solemnizing Officer",
  "SUBSCRIBED",
  "AND",
  "SWORN",
  "before",
  "me",
  "this",
  "day",
  "Philippines, affiant who exhibited to me his Community Tax Cert:",
  "issued",
  "Signature of the Administering Officer",
  "Position{TitlelDesignation",
  "Name in Print",
  "Address",
  "AFFIDAVIT FOR DELAYED REGISTRATION OF MARRIAGE",
  "of legal age",
  "singlelmarriedldivorcedlwidowlwidower, with residence and",
  "postal address",
  "after",
  "having",
  "sworn in accordance with law do hereby depose and say:",
  "That",
  "am the applicant for the delayed registration of",
  "my marriage",
  "with",
  "the",
  "marriage between",
  "and",
  "2. That said marriage was solemnized by",
  "(Solemnizing Officer's name)",
  "under",
  "religious ceremony",
  "civil ceremony",
  "Muslim rites",
  "tribal rites",
  "That the marriage was solemnized:",
  "with marriage license no",
  "issued",
  "under Article",
  "(marriages",
  "of exceptional character);",
  "4. (If the applicant",
  "is either the wife or husband)",
  "That",
  "am",
  "citizen of",
  "and my spouse",
  "is a citizen of",
  "(If the applicant is other than the wife or husband)",
  "That the wife is",
  "citizen of",
  "and",
  "the husband",
  "a citizen of",
  "5. That the reason for the delay in registering",
  "our/their marriage is",
  "That",
  "am executing this affidavit to attest to the truthfulness of the foregoing statements for all Iegal intents and purposes_",
  "truth",
  "whereof,",
  "have  affixed",
  "my",
  "signature",
  "below",
  "this",
  "day",
  "Philippines.",
  "Signature Over Printed Name of Affiant",
  "SUBSCRIBED AND SWORN",
  "to before me this",
  "day of",
  "Philippines, affiant who exhibited to me his Community Tax Cert:",
  "issued on",
  "Signature of the Administering Officer",
  "Position/ Titlel Designation",
  "Name in Print",
  "Address",
  "thal",
  "the",
  "and",
  "day",
  "the",
  "duly"
]
template = {
    # Page 1: Province, City, and Registry No.
    "province": "",
    "city": "",
    "registry_number": "",

    # Husband Information (Page 1)
    "husband_first_name": "",
    "husband_middle_name": "",
    "husband_last_name": "",
    "husband_birth_date": "",
    "husband_birth_city": "",
    "husband_birth_province": "",
    "husband_birth_country": "",
    "husband_age": "",

    # Wife Information (Page 1)
    "wife_first_name": "",
    "wife_middle_name": "",
    "wife_last_name": "",
    "wife_birth_date": "",
    "wife_birth_city": "",
    "wife_birth_province": "",
    "wife_birth_country": "",
    "wife_age": "",

    # Page 2: Husband Information
    "husband_sex": "",
    "husband_citizenship": "",
    "husband_residence_barangay": "",
    "husband_residence_city": "",
    "husband_residence_province": "",
    "husband_residence_country": "",
    "husband_religion": "",
    "husband_civil_status": "",
    "husband_father_name_first": "",
    "husband_father_name_middle": "",
    "husband_father_name_last": "",

    # Page 2: Wife Information
    "wife_sex": "",
    "wife_citizenship": "",
    "wife_residence_barangay": "",
    "wife_residence_city": "",
    "wife_residence_province": "",
    "wife_residence_country": "",
    "wife_religion": "",
    "wife_civil_status": "",
    "wife_father_name_first": "",
    "wife_father_name_middle": "",
    "wife_father_name_last": "",

    # Page 3: Husband Information
    "husband_father_citizenship": "",
    "husband_mother_name_first": "",
    "husband_mother_name_middle": "",
    "husband_mother_name_last": "",
    "husband_mother_citizenship": "",
    "husband_consent_name_first": "",
    "husband_consent_name_middle": "",
    "husband_consent_name_last": "",
    "husband_relationship": "",
    "husband_consent_person_barangay": "",
    "husband_consent_person_city": "",
    "husband_consent_person_province": "",
    "husband_consent_person_country": "",

    # Page 3: Wife Information
    "wife_father_citizenship": "",
    "wife_mother_name_first": "",
    "wife_mother_name_middle": "",
    "wife_mother_name_last": "",
    "wife_mother_citizenship": "",
    "wife_consent_name_first": "",
    "wife_consent_name_middle": "",
    "wife_consent_name_last": "",
    "wife_relationship": "",
    "wife_consent_person_barangay": "",
    "wife_consent_person_city": "",
    "wife_consent_person_province": "",
    "wife_consent_person_country": "",

    # Page 4: Marriage Details
    "place_of_marriage": "",
    "date_of_marriage": "",
    "time_of_marriage": "",
    "cert_husband_name": "",
    "cert_wife_name": "",
    "marriage_settlement": "",
    "cert_day": "",
    "cert_month": "",
    "cert_year": "",

    # Page 5: Certification and Officer Details
    "certification": "",
    "marriage_license_no": "",
    "marriage_issued_on": "",
    "marriage_issued_at": "",
    "executive_order": "",
    "officer_position": "",
    "officer_religion": "",
    "witness1_name": "",
    "witness2_name": "",
    "witness3_name": "",
    "witness4_name": "",

    # Page 6: Registrar Details
    "received_by_name": "",
    "received_by_title": "",
    "received_by_date": "",
    "registrar_name": "",
    "registrar_title": "",
    "registrar_date": "",
    "remarks_annotation": "",

    # Page 7: Additional Witnesses and Affidavit
    "witness5_name": "",
    "witness6_name": "",
    "witness7_name": "",
    "witness8_name": "",
    "witness9_name": "",
    "witness10_name": "",
    "witness11_name": "",
    "witness12_name": "",
    "affidavit_officer_name": "",
    "affidavit_officer_organization": "",
    "affidavit_officer_address": "",
    "statement1_party1": "",
    "statement1_party2": "",
    "statement2a": 0,
    "statement2b": 0,
    "statement2c": 0,
    "statement2c_party1": "",
    "statement2c_party2": "",
    "statement2d": 0,
    "statement2e": 0,

    # Page 8: Affidavit and Sworn Details
    "affidavit_day": "",
    "affidavit_month": "",
    "affidavit_year": "",
    "affidavit_place": "",
    "sworn_day": "",
    "sworn_month": "",
    "sworn_year": "",
    "sworn_at": "",
    "sworn_issued_on": "",
    "sworn_issued_on2": "",
    "sworn_issued_at": "",
    "admin_officer_name": "",
    "admin_officer_title": "",
    "admin_officer_address": "",

    # Page 9: Affiant and Ceremony Details
    "affiant_name": "",
    "affiant_civil_status": "",
    "affiant_address": "",
    "statement1_option_a": 0,
    "statement1_marriage_with": "",
    "statement1_place_a": "",
    "statement1_date_a": "",
    "statement1_option_b": 0,
    "statement1_spouse_name_1": "",
    "statement1_spouse_name_2": "",
    "statement1_place_b": "",
    "statement1_date_b": "",
    "solemnizing_officer": "",
    "ceremony_religious": 0,
    "ceremony_civil": 0,
    "ceremony_muslim": 0,
    "ceremony_tribal": 0,
    "marriage_with_license": 0,
    "marriage_license_no_page9": "",
    "marriage_issued_on_page9": "",
    "marriage_issued_at_page9": "",
    "marriage_under_article": 0,
    "article_number": "",
    "citizen_applicant": "",
    "citizen_spouse": "",
    "citizen_applicant2": "",
    "citizen_spouse2": "",
    "reason_for_delay": "",
    "affidavit_day_page9": "",
    "affidavit_month_page9": "",
    "affidavit_year_page9": "",
    "affidavit_place_page9": "",

    # Page 10: Sworn Details
    "sworn_day_page10": "",
    "sworn_month_page10": "",
    "sworn_year_page10": "",
    "sworn_place_page10": "",
    "sworn_issued_on_page10": "",
    "sworn_issued_on_page102": "",
    "sworn_issued_at_page10": "",
    "administering_officer_name": "",
    "officer_position_page10": "",
    "officer_address_page10": ""
}

def remove_data_placeholders(source_list, reference_list, threshold=70):
  cleaned=[]
  junk_pattern = re.compile(r"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{1,5}$")
  numbered_dot_pattern = re.compile(r"^\d+\.$")
  noisy_symbol_pattern = re.compile(r"[^\w\s.'-]")

  for src in source_list:
      s = src.strip()

      if " " in s:
          parts = s.split()
          first_word = parts[0].lower().rstrip(":")
          if "/" in first_word or first_word in reference_list:
              # only keep the part after the label
              old_value = s
              s = " ".join(parts[1:])
              logger.info(f"[DEBUG] Split merged OCR text: '{old_value}' → '{s}'")

      if "(" in s or ")" in s:
          continue

      if junk_pattern.match(s):
          continue

      if len(s) < 2 or re.fullmatch(r"[^A-Za-z0-9]+", s):
          continue

      if noisy_symbol_pattern.search(s):
          continue
      
      if numbered_dot_pattern.match(s):
          continue

      match = process.extractOne(s, reference_list, scorer=fuzz.token_set_ratio)
      if match:
          _, score, _ = match
          if score >= threshold:
              continue
      cleaned.append(s)

  return cleaned

def generate_template(template: dict, ocr_list: list):
  filled = template.copy()
  keys = list(filled.keys())

  numeric_keys = []
  valid_values = {}

  ocr_index = 0
  key_index = 0
  while key_index < len(keys) and ocr_index < len(ocr_list):
    key = keys[key_index]
    value = ocr_list[ocr_index].strip() if isinstance(ocr_list[ocr_index], str) else ocr_list[ocr_index]
    
    filled[key] = value
    key_index += 1
    ocr_index += 1
  
  return filled

def marriageParse(ocr_text):
  logger.info(ocr_text)
  cleaned = remove_data_placeholders(ocr_text, default_keywords)
  logger.info("[remove_data_placeholders] %s", cleaned)
  response = generate_template(template, cleaned)
  logger.info("[parsed] %s", response)
  
  return response